- name: Adds prerequisites
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-software-properties

- name: Adds glusterfs PPA
  apt_repository:
    repo: 'ppa:semiosis/ppa'

- name: Install server
  apt:
    pkg: glusterfs-server
    state: present
  register: __gluster_installed

# Sometimes glusterfs-server doesn't come up nicely :(
- name: Force glusterfs-server restart after install
  service:
    name: glusterfs-server
    state: stopped
  when: __gluster_installed|changed

- name: Force start glusterfs-server after install
  service:
    name: glusterfs-server
    state: started
  when: __gluster_installed|changed

- name: Ping peers before probes
  command: ping -c3 {{ item }}-{{ gluster_interface }}
  with_items: play_hosts
  changed_when: false

- name: Shows first gluster server
  debug: msg="servers[0] *{{ groups[gluster_servers_group][0]}}*"
  tags: glusterfs:probe

- name: Show inventory hostname
  debug: msg="inventory  *{{inventory_hostname}}*"
  tags:
    - glusterfs:probe

- name: Probe peers
  shell: "gluster peer probe {{ item }}-{{ gluster_interface }}"
  with_items: "{{ ansible_play_hosts }}"
  when: item != inventory_hostname and 
    inventory_hostname in groups[gluster_servers_group][0]
  register: __gluster_probe
  changed_when: '"already in peer list" not in __gluster_probe.stdout'
  tags:
    - glusterfs:probe

