- name: Adds prerequisites
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - python-software-properties

- name: Adds glusterfs PPA
  apt_repository: repo='ppa:semiosis/ppa'

- name: Install server
  apt: >
    pkg=glusterfs-server
    state=latest
  register: gluster_installed

- debug: msg="{{ play_hosts | join(',') | regex_replace('([^,]*)', '\\1-eth1')}}"

# Sometimes glusterfs-server doesn't come up nicely :(
- name: Force glusterfs-server restart after install
  service: name=glusterfs-server state=stopped
  when: gluster_installed|changed
- name: Force start glusterfs-server after install
  service: name=glusterfs-server state=started
  when: gluster_installed|changed

- name: Ping peers before probes
  command: ping -c3 {{ item }}-eth1
  with_items: play_hosts
  changed_when: false

- name: Probe peers
  shell: "gluster peer probe {{ item }}-eth1; sleep 10"
  with_items: play_hosts
  when: "item != inventory_hostname and inventory_hostname in gluster_servers[0]"
  register: gluster_probe
  changed_when: '"already in peer list" not in gluster_probe.stdout'
  tags: glusterfs_probe
